--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.341.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29.03.2021 13:01:23
-- Server version: 5.5.5-10.1.47-MariaDB-0ubuntu0.18.04.1
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(1, 35, 'Pfötchen', 1, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 1);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(2, 35, 'Platz', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 2);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(3, 35, 'Sitz', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, 3);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(4, 35, 'Sitz', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9, 4);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(5, 35, 'Sitz', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 5);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(8, 35, 'Peng', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 8);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(10, 35, 'Pfötchen', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 1);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(11, 35, 'Platz', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 2);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(12, 35, 'Sitz', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, 3);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(13, 35, 'Sitz', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9, 4);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(14, 35, 'Sitz', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 5);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(17, 35, 'Peng', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 8);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(25, 35, 'Pfötchen', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 1);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(26, 35, 'Platz', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 2);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(27, 35, 'Sitz', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, 3);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(28, 35, 'Sitz', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9, 4);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(32, 35, 'Peng', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 8);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(76, 35, 'Sitz', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, 3);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(77, 35, 'Sitz', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9, 4);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(78, 35, 'Sitz', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 5);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(83, 35, 'Pfötchen', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 1);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(84, 35, 'Platz', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 2);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(90, 35, 'Peng', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 8);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(119, 35, 'Pfötchen', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4, 1);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(120, 35, 'Platz', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 2);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(126, 35, 'Peng', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 8);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(157, 35, 'Sitz', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8, 3);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(158, 35, 'Sitz', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9, 4);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(159, 35, 'Sitz', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 5);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(246, 35, 'Sitz', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11, 4);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(247, 35, 'Sitz', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11, 4);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(248, 35, 'Sitz', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11, 4);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(249, 35, 'Sitz', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11, 4);
INSERT INTO apps_entw.tb_plan(id, taid, verhalten, schritt, ort, ablenkung, entfernung, setting, promptheit, erfolgsrate, geschwindigkeit, genauigkeit, clickpunkt, futtterpunkt, lockpunkt, wenn, dann, pid, zid) VALUES
(250, 35, 'Sitz', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11, 4);